import Head from "next/head";
import { useEffect, useState } from "react";
// Services
import { getAll, getAllByName } from "@services/httpRequest";
// Models
import { Photo } from "@models/photo";
// Utils
import { useDebouncer } from "@utils/hooks/useDebouncer";
// Components
import { Loading } from "@components/loading";
import { HeaderMenu } from "@components/headerMenu";
import { Photos } from "@components/photos";
import { Footer } from "@components/footer";
// Styled components
import { Container } from "@styles/shared/container";

export const getStaticProps = async () => {
  const api = process.env.URL_API;
  const data = await getAll(api);
  return {
    props: {
      api: api ? api : "",
      data,
    },
  };
};

interface HomeProps {
  api: string;
  data: Photo[];
}

const Home = ({ api, data }: HomeProps) => {
  const [searchInput, setSearchInput] = useState({
    searchText: "",
    dirtyInput: true,
  });
  const searchTerm = useDebouncer(searchInput.searchText, 500);
  const [photos, setPhotos] = useState<Photo[]>(data);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (searchInput.searchText === "" && searchInput.dirtyInput === false) {
      setLoading(true);
      getAll(api)
        .then((data) => {
          setPhotos(data);
          setLoading(false);
        })
        .catch((error) => console.log(error));
    }
    if (searchTerm !== "") {
      setLoading(true);
      getAllByName(api, searchTerm)
        .then((data) => {
          setPhotos(data);
          setLoading(false);
        })
        .catch((error) => console.log(error));
    }
  }, [searchTerm]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        {loading ? (
          <Loading />
        ) : (
          <>
            <HeaderMenu
              api={api}
              setSearchInput={setSearchInput}
              searchText={searchInput.searchText}
            />
            <Photos photos={photos} api={api} />
          </>
        )}
        <Footer />
      </Container>
    </div>
  );
};

export default Home;
